### ISSUE TITLE
Wire in Goals Data

### ISSUE THREAD

**Issue by ferret1964** [MccCareplan/providersmartapp#109]
Update the Goals pane to fetch actual data from the API. Both Patient and Clinical goals would be populated. 
The Goals should have three columns Rank, Goal, and Status... The {api}/goalsummary will return a goal list structure. The activeClinicalGoals and activePatientGoals will form the data source. Further the activeTargets list provides the source for rows in the 
Target Laboratory/Clinical Values table -Which should be populated with the Measure and Target, which a neutral style. In another story the most recent result for each items will be requested and the Result and Test Data and Style updated depending on the Result.

Data Sources:

Resource	Queries
Goal	FHIR: {base}/Goal/?subject={subject-id}
Api: {apibase}/goalsummary/?{subject-id}
Api: {apibase}/goal/{goal-id}

Data Map
Field	Source Resource/Field	Notes
Rank	Goal	Based on Priority Highest First (Note that 
Goal	Goal	Filtered by those goals not expressed by the patient

Status	Goal	Combination of Lifecycle Status & Achievement Status.

FHIR Resource Reference: https://www.hl7.org/fhir/goal.html
API Public Documents: http://mcc-niddk-backend.wl.r.appspot.com/swagger-ui/index.html?configUrl=/api-docs/swagger-config
Core Schemas:   GoalLists, Gool Summary, Goal Target

Value Sets required

Goal Priority:   high-priority | medium-priority | low-priority 
   (see https://www.hl7.org/fhir/valueset-goal-priority.html)
Goal Lifecycle Status: 	proposed | planned | accepted | active | on-hold | completed | cancelled | entered-in-error | rejected
   {see https://www.hl7.org/fhir/valueset-goal-status.html)
Goal Achievement Status: in-progress | improving | worsening | no-change | achieved | sustaining | not-achieved | no-progress | not-attainable
   (see https://www.hl7.org/fhir/valueset-goal-achievement.html)

Target Types:

..... detailQuantity			Quantity	
..... detailRange			Range	
..... detailCodeableConcept			CodeableConcept	
..... detailString			string	
..... detailBoolean			boolean	
..... detailInteger			integer	
..... detailRatio			Ratio

**Comment by steve1mercury** [comment]
In target-values.component.ts, formatTargetValue method.
Coded Formatting logic for Quantity and Range.

Other value types not coded.
Need sample target data for  :
CodeableConcept
Ration
Period
Range
Date
Time
DateTime
SampledData
DurationValue
TimingValue
InstantValue
IdentifierValue
