### ISSUE TITLE
Fetch and Update Targets

### ISSUE THREAD

**Issue by ferret1964** [MccCareplan/providersmartapp#111]
Using the APIs developed in #108, Make Async requests for each Measure in the table. If there is a most recent result update the row to indicate the value, test date. If the value is within target then style the row as Green,  Unmatched targets should be yellow.  

When there is no target value the we can use the observation-interpretation as a guide line for system color. We may also want to to also Style as red anything flagged as Critical: See https://www.hl7.org/fhir/valueset-observation-interpretation.html 

The API call is 
{apibase}/find/latest/observation?subject={subjected}&code={code}

Returns a single Mcc Observation.  The Value of the observation is of variable type. The most common form will be a Quantity, Full list of possible types are:

Quantity,  CodeableConcept, String, Boolean, Integer, Range, Ratio, SampledData, Time, DateTime, Period

FHIR Resource reference: https://www.hl7.org/fhir/observation.html

Note: A complication is potential of the use of the Observation Component... Selected observations (e.g. blood pressure) will use a higher level code to bundle together related values (like systolic and diastolic blood pressure). The API search was patched on 9/4/2020 at 12:30 to search the components when a test is not found in the primary code field. The safest was to detect this condition is to check the code one the observation for a match, although the absence of a primary value is also a good clue. In this case the consumer will need to search the observation components for the one that matches the requested code.  

Example:

{{Server}}/find/latest/observation/?subject=cc-pat-pnoelle&code=4548-4

returns

{
    "code": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "4548-4",
                "display": "4548-4"
            }
        ],
        "text": "Hemoglobin A1c"
    },
    "status": "final",
    "value": {
        "valueType": "Quantity",
        "integerValue": 0,
        "booleanValue": false,
        "quantityValue": {
            "unit": "%",
            "value": "8.8",
            "system": "http://unitsofmeasure.org/",
            "code": "%"
        }
    },
    "category": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                    "code": "laboratory",
                    "display": "laboratory"
                }
            ],
            "text": "Laboratory"
        }
    ],
    "fhirid": "cc-obs-pnoelle-lab-a1c-6"
}

---- Example with Components -----
{{Server}}/find/latest/observation/?subject=cc-pat-pnoelle&code=8462-4

{
    "code": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "85354-9",
                "display": "85354-9"
            }
        ]
    },
    "status": "final",
    "components": [
        {
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "8480-6",
                        "display": "8480-6"
                    }
                ]
            },
            "value": {
                "valueType": "Quantity",
                "integerValue": 0,
                "booleanValue": false,
                "quantityValue": {
                    "unit": "mmHg",
                    "value": "147",
                    "system": "http://unitsofmeasure.org",
                    "code": "mm[Hg]"
                }
            }
        },
        {
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "8462-4",
                        "display": "8462-4"
                    }
                ]
            },
            "value": {
                "valueType": "Quantity",
                "integerValue": 0,
                "booleanValue": false,
                "quantityValue": {
                    "unit": "mmHg",
                    "value": "83",
                    "system": "http://unitsofmeasure.org",
                    "code": "mm[Hg]"
                }
            }
        }
    ],
    "category": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                    "code": "vital-signs",
                    "display": "vital-signs"
                }
            ],
            "text": "Vital Signs"
        }
    ],
    "fhirid": "cc-obs-pnoelle-bp-6"
}

**Comment by steve1mercury** [comment]
I am currently working on #111 Fetch and Update Targets
I am stuck on trying to figure out how to code dataservice.getMostRecentObservationResult  
as shown here referenced in target-values.component.html

<td mat-cell *matCellDef="let target">{{dataservice.getMostRecentObservationResult(dataservice.currentPatientId, target.measure.coding.code) | async }}</td>
I haven't been able to find any example of an async http get performed for a mat-cell while a mat-table data source is being populated.  I'm not sure if it's possible, so I'll have to come up with something else.

I have run out of time today.  I'm not sure I will be able to work on it any more this weekend.

I have completed #109 Wire in Goals data, pushed and merged the changes to the providersmartapp repo.   When I initially did the push and merge, I did not notice that everything did not got pushed up.  So I had to revert the push and redo it.   The current master contains the changes for #109 Wire in Goals data.

**Comment by steve1mercury** [comment]
this makes the UI hang.

In goals-data-service.service.ts
async getMostRecentObservationResult(patientId: string, code: string): Promise<string> {
  if (patientId && code) {
    const url = `${environment.mccapiUrl}${this.observationURL}?subject=${patientId}&code=${code}`;
    const observation = await this.http.get<MccObservation>(url).toPromise();
    return observation.value.quantityValue.value;
  } else {
    return '';
  }
}

In target-values.component.html

<td mat-cell *matCellDef="let target"
    >{{goalsdataservice.getMostRecentObservationResult(dataservice.currentPatientId, target.measure.coding.code) | async }}</td>
_________________________
If I take the async pipe off of the previous mat-cell declaration, then you get this in the UI..

Screen Shot 2020-09-05 at 7.51.36 PM.png

**Comment by ferret1964** [comment]
Ok - Thanks - Can you at least push your branch up to Github and Maybe I can give it a try.

**Comment by steve1mercury** [comment]
Added coding into getPatientGoals in data.service.ts to load targetValues[] object in data service.  
Still need to figure out how to call getMostRecentObservationResult in goals-data-service.service.ts : getPatientGoals()   for each activetarget.

**Comment by steve1mercury** [comment]
just pushed more commits to feature_111 branch.
still can't get the Target Laboratory / Clinical Values datagrid to populate.

The targetValues: TargetValue[]; object does get populated...

Screen Shot 2020-09-07 at 7.22.53 PM.png

But the mat-table is not showing the data.

Here is the code in the dataservice that loads the Goal targets and the targetValues.

async getPatientGoals(): Promise<boolean> {
  /*
  this.goalsdataservice.getGoals(this.currentPatientId)
    .subscribe(goals => {
      // this.targetValues = [];
      this.goals = goals;
      console.log('In DataService.getPatientGoals: this.goals: ', this.goals);
      this.goalsdataservice.getPatientGoalTargets(this.currentPatientId, goals)
        .subscribe(tv => {
          console.log('in getPatientGoals, in getPatientGoalTargets subscribe.  tv= ', tv);
          this.targetValues = tv;
          console.log('in getPatientGoals, in getPatientGoalTargets subscribe.  this.targetValues= ', this.targetValues);
        });
    });
    */

  this.goalsdataservice.getGoals(this.currentPatientId)
    .pipe(
      tap(g => this.goals = g),
      concatMap(g => this.goalsdataservice.getPatientGoalTargets(this.currentPatientId, g))
    ).subscribe(tv => {
    console.log('in getPatientGoals, in getPatientGoalTargets subscribe.  tv= ', tv);
    this.targetValues = tv;
    console.log('in getPatientGoals, in getPatientGoalTargets subscribe.  this.targetValues= ', this.targetValues);
  });

  return true;
}

**Comment by ferret1964** [comment]
Thanks - I thought you were hands off on the code…. I will have to see if your changes conflict with mine…. 

Any idea how I can programmatically cause the patient context to change? I am now getting the current patient/subjeect id from the smart-on-fhir-launch, but I can’t seem to the display to fetch the data for the new patient.

**Comment by steve1mercury** [comment]
Hi Jerry,Sorry, If I you made changes to branch  Fetch and Update Targets (#111), before I did the last commit.  I didn't communicate that to you that I was still working on it.  Sorry, I thought I was going to be able to make the targets grid populate before I had to quit for the night.  I hope it did not cause you problems.
To select a patient upon loading the app, I think you need to set the currentSubjectId in ngOnInit() in the app.component.ts file.  To get the subjectID from the URL, I believe some routing coding will need to be put into app.component.ts similar to this...

// ...
import { ActivatedRoute } from '@angular/router';
import 'rxjs/add/operator/filter';

@Component({ ... })
export class ProductComponent implements OnInit {
  order: string;
  constructor(private route: ActivatedRoute) { }

  ngOnInit() {
    this.route.queryParams
      .filter(params => params.order)
      .subscribe(params => {
        console.log(params); // { order: "popular" }

        this.order = params.order;
        console.log(this.order); // popular
      }
    );
  }
}I got the above from How To Use Query Parameters in Angular | DigitalOcean

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How To Use Query Parameters in Angular | DigitalOcean

In this article, we will reference an example of an application that displays a list of products to understand h...
 |

 |

 |


-Steve




    On Monday, September 7, 2020, 09:30:34 PM PDT, Jerry Goodnough <notifications@github.com> wrote:  
 
 

Thanks - I thought you were hands off on the code…. I will have to see if your changes conflict with mine…. 

Any idea how I can programmatically cause the patient context to change? I am now getting the current patient/subjeect id from the smart-on-fhir-launch, but I can’t seem to the display to fetch the data for the new patient.

**Comment by steve1mercury** [comment]
https://www.digitalocean.com/community/tutorials/angular-query-parameters

**Comment by steve1mercury** [comment]
Got the Population of the Target Laboratory/Clinical Values Datagrid working.  Also coded the logic to check for Observation Quantity against Target Quantity Value and Range Value, out of range highlights the row in the datagrid in Yellow.  
Put in the logic to highlight the grid row in red if 'critical' status encountered in the Observation.  The test data doesn't contain any critical observations so I'm not sure that that will work.

Also,  the latest mcc-api on the master branch doesn't seem to contain the following data in the observation URL :

/find/latest/observation?subject=cc-pat-betsy&code=4548-4 

this node is not yet being returned in the JSON:

    "effective": {
        "type": "DateTime",
        "dateTime": {
            "rawDate": "2018-12-30T08:00:00.000+00:00",
            "date": "12/30/2018"
        }
    },

Note:  Test data does not have samples of other value types, so currently Quantity and Range Value types are the only ones coded that will highlight the row.

I coded and commented out the following code in the goals-data-service.service.ts that will access the rawDate field when it becomes available:

              /*  todo:  uncomment after obs.effective is added to MccObservation object
              if (obs.effective !== undefined) {
                if (obs.effective.type === 'DateTime') {
                  observationDate = obs.effective.date;
                }
              }
              */

The Target Laboratory/Clinical Values datagrid appears as follows:  Note all of the data in this example is out of range, and all of the returned rows in the grid are highlighted in yellow.

![Screen Shot 2020-09-10 at 4.19.59 PM.png](https://images.zenhubusercontent.com/5f2d727f11666984fc883755/b4d84db3-df12-4b70-b50f-77a210a8a264)

**Comment by steve1mercury** [comment]
Pushed the above changes into the feature_111_Update_Targets_With_Observation Branch.

Did not create a Pull request.
