### ISSUE TITLE
Minor Goals related UI issues

### ISSUE THREAD

**Issue by ferret1964** [MccCareplan/providersmartapp#114]
1) Rename tab title to be Goals and Preferences
2) Rename Clinical Goals to Partitioner  Goals
3) Add Goal Columns for Created, Target Date, Status
4) Change Rank to Priority (High, Medium, Low) - May a Visual Indication rather then text
5) Fix Duplicate RENAL text on Patient RRT area
6) Add the following options for RRT
     Hemodialysis
     Peritoneal Dialysis
     Transplant
     Supportive Care with No RRT
     Undecided
     Other

**Comment by steve1mercury** [comment]
![Screen Shot 2020-09-03 at 3.10.44 PM.png](https://images.zenhubusercontent.com/5f2d727f11666984fc883755/80866058-3f25-42cf-84c7-02cfe751f4fa)
