### ISSUE TITLE
Replace ng2-charts library with basic chart.js libray in building Blood pressure chart

### ISSUE THREAD

**Issue by steve1mercury** [MccCareplan/providersmartapp#140]
The current coding using ng2-charts library may have a bug where the X axis is not being formatted correctly.

Currently, an x axis label is being generated for each data point.  The datapoints should be interspersed between month labels in the X Axis.  
Try using the basic Javascript Chart.js library and not use the ng2-charts Angular library to see if it makes a difference.

**Comment by steve1mercury** [comment]
Did not have to replace ng2-Charts library.  Determined the problem was that the [options] being passed into the baseChart on bpgraph.component.html was not declared as a ChartOptions object.   The options were being passed in as a string, and were not being interpreted correctly.  Also, the formatting of the options in utility-functions.js was not passing in the yAxes and xAxes scales settings correctly.

**Comment by steve1mercury** [comment]
![Screen Shot 2020-10-16 at 11.03.35 AM.png](https://images.zenhubusercontent.com/5f2d727f11666984fc883755/3c7c8b37-68ad-41a4-b99b-4beada1967ba)

Did not have to replace  the ng2 charts library. 
Determined the problem was that the options passed into the baseChart on bpgraph component was not declared as a ChartOptions object.   The options were being passed in as a string, and were not being interpreted correctly.  
Also, the formatting of the options in utility-functions  was not passing in the yAxes and xAxes scales settings correctly.

**Comment by steve1mercury** [comment]
Fixed problem using ng2-charts library.   The options object was not declared as a ChartOptions object in the vitalSigns.ts file.
Also, did not format the options correctly when creating the ChartOptions object.

![Screen Shot 2020-10-16 at 11.03.35 AM.png](https://images.zenhubusercontent.com/5f2d727f11666984fc883755/b4cf0ebf-27b9-4e2f-a477-090ddcf3ee57)

**Comment by ferret1964** [comment]
Cool... is the same error on out other uses (I bet the answers is yes). If so can you create a story to fix the others?

**Comment by steve1mercury** [comment]
Hi Jerry,
yes, this should be the fix to the ng2-charts problems.  I will create a story to fix.Thanks!-Steve
    On Friday, October 16, 2020, 12:09:18 PM PDT, Jerry Goodnough <notifications@github.com> wrote:  
 
 


Cool... is the same error on out other uses (I bet the answers is yes). If so can you create a story to fix the others?

**Comment by steve1mercury** [comment]
Seems to be working now.  But the start/end X-Axis change I made to utility-functions.ts didn't get into this PR.  It will be pulled in in the next PR for feature #132

![Screen Shot 2020-10-22 at 11.16.04 AM.png](https://images.zenhubusercontent.com/5f2d727f11666984fc883755/172fee8a-f417-4b2d-aede-bace84bca131)
